#Requires -Version 5.1
<#
.SYNOPSIS
    Build, deploy, and run the WhisperKit instrumented test on a connected Android device.

.DESCRIPTION
    1. Verify an ADB device is connected
    2. Verify the test video exists at D:\Videos\Vol_election.mp4
    3. Download ggml-tiny.bin from HuggingFace if not already cached
    4. Build the app APK + test APK (assembleDebug + assembleDebugAndroidTest)
    5. Install both APKs on the device
    6. Push video to /sdcard/Movies/
    7. Push model to app private files dir via run-as
    8. Grant required runtime permissions
    9. Run the instrumented test
   10. Pull and display results

.NOTES
    Target: Pixel 7 Pro (Android 14, arm64-v8a), package dev.ffmpegkit.test
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ─────────────────────────────────────────────── constants ──

$ProjectRoot   = $PSScriptRoot
$VideoSrc      = "D:\Videos\Vol_election.mp4"
$VideoDevice   = "/sdcard/Movies/Vol_election.mp4"
$ModelUrl      = "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin"
$ModelCache    = "$env:TEMP\ggml-base.bin"
$ModelDevTmp   = "/data/local/tmp/ggml-base.bin"
$ModelDevApp   = "/data/data/dev.ffmpegkit.test/files/ggml-base.bin"
$ResultsDevice = "/sdcard/Movies/whisper_test_results.txt"
$ResultsLocal  = "$ProjectRoot\whisper_test_results.txt"

# SRT subtitle files generated by the test (app-specific external storage — no permission needed)
$SrtDeviceBase = "/sdcard/Android/data/dev.ffmpegkit.test/files"
$SrtLocalBase  = "D:\Videos"
# adb is in the Android SDK platform-tools; not always in PowerShell PATH
$AdbExe        = "C:\Users\infol\AppData\Local\Android\Sdk\platform-tools\adb.exe"
if (-not (Test-Path $AdbExe)) { $AdbExe = "adb" }  # fallback to PATH

$AppPackage    = "dev.ffmpegkit.test"
$TestPackage   = "dev.ffmpegkit.test.test"
$TestClass     = "dev.ffmpegkit.test.WhisperKitInstrumentedTest"
$TestRunner    = "androidx.test.runner.AndroidJUnitRunner"
$AppApk        = "$ProjectRoot\app\build\outputs\apk\debug\app-debug.apk"
$TestApk       = "$ProjectRoot\app\build\outputs\apk\androidTest\debug\app-debug-androidTest.apk"

# ─────────────────────────────────────────────── helpers ──

function Write-Step { param([string]$Msg)
    Write-Host "`n>>> $Msg" -ForegroundColor Cyan
}

function Write-OK { param([string]$Msg)
    Write-Host "    [OK] $Msg" -ForegroundColor Green
}

function Write-Fail { param([string]$Msg)
    Write-Host "`n[ECHEC] $Msg" -ForegroundColor Red
}

function Invoke-ADB {
    param([string[]]$AdbArgs, [string]$Description = "")
    Write-Host "    $ adb $($AdbArgs -join ' ')"
    & $AdbExe @AdbArgs
    if ($LASTEXITCODE -ne 0) {
        Write-Fail "adb $($AdbArgs -join ' ') failed (code $LASTEXITCODE) — $Description"
        exit 1
    }
}

# ─────────────────────────────────────────────── step 1: device check ──

Write-Step "1/13 — Checking ADB device"

$AdbDevices = & $AdbExe devices 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Fail "adb not found or ADB server failed to start. Is ADB in PATH?"
    exit 1
}

# Parse lines: skip header and empty lines, look for an online device
$ConnectedDevices = ($AdbDevices | Select-Object -Skip 1) |
    Where-Object { $_ -match '\bdevice\b' -and $_ -notmatch 'offline' }

if (-not $ConnectedDevices) {
    Write-Fail "No Android device connected (or device is offline/unauthorized)."
    Write-Host "Run: & $AdbExe devices"
    Write-Host $AdbDevices
    exit 1
}

$FirstDevice = @($ConnectedDevices)[0]
Write-OK "Device found: $($FirstDevice.ToString().Trim())"

# ─────────────────────────────────────────────── step 2: video check ──

Write-Step "2/13 — Checking test video"

if (-not (Test-Path $VideoSrc)) {
    Write-Fail "Video not found at $VideoSrc"
    Write-Host "Place the test video there before running this script."
    exit 1
}

$VideoSize = (Get-Item $VideoSrc).Length / 1MB
Write-OK "Video found: $VideoSrc ($([math]::Round($VideoSize, 1)) MB)"

# ─────────────────────────────────────────────── step 3: download model ──

Write-Step "3/13 — Ensuring ggml-tiny.bin is cached"

if (Test-Path $ModelCache) {
    $ModelSize = (Get-Item $ModelCache).Length / 1MB
    Write-OK "Already cached at $ModelCache ($([math]::Round($ModelSize, 1)) MB)"
} else {
    Write-Host "    Downloading from HuggingFace — this is ~75 MB, please wait..."
    try {
        Invoke-WebRequest -Uri $ModelUrl -OutFile $ModelCache -UseBasicParsing `
            -Headers @{ "User-Agent" = "Mozilla/5.0" }
        $ModelSize = (Get-Item $ModelCache).Length / 1MB
        Write-OK "Downloaded: $ModelCache ($([math]::Round($ModelSize, 1)) MB)"
    } catch {
        Write-Fail "Download failed: $_"
        exit 1
    }
}

# ─────────────────────────────────────────────── step 4: build APKs ──

Write-Step "4/13 — Building debug APK + androidTest APK"

# Generate gradlew.bat if missing (wrapper properties already present)
$GradlewBat = "$ProjectRoot\gradlew.bat"
if (-not (Test-Path $GradlewBat)) {
    Write-Host "    gradlew.bat not found — generating Gradle wrapper..."
    Push-Location $ProjectRoot
    & gradle wrapper --gradle-version 8.6 2>&1
    Pop-Location
    if ($LASTEXITCODE -ne 0) {
        Write-Fail "gradle wrapper generation failed. Is 'gradle' in PATH?"
        exit 1
    }
    Write-OK "gradlew.bat generated"
}

Push-Location $ProjectRoot
Write-Host "    Running: .\gradlew.bat assembleDebug assembleDebugAndroidTest"
& ".\gradlew.bat" assembleDebug assembleDebugAndroidTest
$GradleExit = $LASTEXITCODE
Pop-Location

if ($GradleExit -ne 0) {
    Write-Fail "Gradle build failed (exit $GradleExit)"
    exit 1
}

if (-not (Test-Path $AppApk)) {
    Write-Fail "App APK not found after build: $AppApk"
    exit 1
}
if (-not (Test-Path $TestApk)) {
    Write-Fail "Test APK not found after build: $TestApk"
    exit 1
}

Write-OK "APKs built successfully"

# ─────────────────────────────────────────────── step 5: install app APK ──

Write-Step "5/13 — Installing app APK"
Invoke-ADB -AdbArgs @("install", "-r", $AppApk) -Description "& $AdbExe install app APK"
Write-OK "App APK installed"

# ─────────────────────────────────────────────── step 6: install test APK ──

Write-Step "6/13 — Installing test APK"
Invoke-ADB -AdbArgs @("install", "-r", $TestApk) -Description "& $AdbExe install test APK"
Write-OK "Test APK installed"

# ─────────────────────────────────────────────── step 7: push video ──

Write-Step "7/13 — Pushing video to device"

# Ensure /sdcard/Movies/ exists
& $AdbExe shell mkdir -p /sdcard/Movies/ 2>&1 | Out-Null
Invoke-ADB -AdbArgs @("push", $VideoSrc, $VideoDevice) -Description "& $AdbExe push video"
Write-OK "Video pushed to $VideoDevice"

# ─────────────────────────────────────────────── step 8: push model ──

Write-Step "8/13 — Pushing model to app private files dir"

# First push to /data/local/tmp/ (world-accessible staging area)
Invoke-ADB -AdbArgs @("push", $ModelCache, $ModelDevTmp) -Description "& $AdbExe push model to /data/local/tmp/"
Write-OK "Model staged at $ModelDevTmp"

# Ensure the app's files dir exists (created on first launch; mkdir is safe if it already exists)
Write-Host "    $ & $AdbExe shell run-as $AppPackage mkdir -p files"
& $AdbExe shell run-as $AppPackage mkdir -p files 2>&1 | Out-Null

# Copy model into the app's private files dir via run-as
Write-Host "    $ & $AdbExe shell run-as $AppPackage cp $ModelDevTmp $ModelDevApp"
$CpResult = & $AdbExe shell run-as $AppPackage cp $ModelDevTmp $ModelDevApp 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Fail "run-as cp failed: $CpResult"
    Write-Host "NOTE: 'run-as' requires a debuggable build. The app APK must be a debug build."
    exit 1
}
Write-OK "Model copied to $ModelDevApp"

# Clean up staging copy
& $AdbExe shell rm -f $ModelDevTmp 2>&1 | Out-Null

# ─────────────────────────────────────────────── step 9: grant permissions ──

Write-Step "9/13 — Granting runtime permissions"

Write-Host "    Granting READ_MEDIA_VIDEO..."
& $AdbExe shell pm grant $AppPackage android.permission.READ_MEDIA_VIDEO 2>&1
# pm grant exits 1 on API levels that don't have this permission — ignore
Write-OK "READ_MEDIA_VIDEO granted (or not applicable on this API level)"

Write-Host "    Granting WRITE_EXTERNAL_STORAGE..."
& $AdbExe shell pm grant $AppPackage android.permission.WRITE_EXTERNAL_STORAGE 2>&1
Write-OK "WRITE_EXTERNAL_STORAGE granted (or not applicable)"

Write-Host "    Granting READ_EXTERNAL_STORAGE..."
& $AdbExe shell pm grant $AppPackage android.permission.READ_EXTERNAL_STORAGE 2>&1
Write-OK "READ_EXTERNAL_STORAGE granted (or not applicable)"

# ─────────────────────────────────────────────── step 10: also grant to test package ──

Write-Step "10/13 — Granting runtime permissions to test package"

& $AdbExe shell pm grant $TestPackage android.permission.READ_MEDIA_VIDEO 2>&1
& $AdbExe shell pm grant $TestPackage android.permission.WRITE_EXTERNAL_STORAGE 2>&1
& $AdbExe shell pm grant $TestPackage android.permission.READ_EXTERNAL_STORAGE 2>&1
Write-OK "Permissions granted to test package"

# ─────────────────────────────────────────────── step 11: run test ──

Write-Step "11/13 — Running instrumented test (timeout: 10 min)"
Write-Host "    Class: $TestClass"
Write-Host "    Runner: $TestRunner"
Write-Host ""

$InstrumentArgs = @(
    "shell", "am", "instrument",
    "-w", "-r",
    "-e", "class", $TestClass,
    "$TestPackage/$TestRunner"
)

Write-Host "    $ adb $($InstrumentArgs -join ' ')"
Write-Host ""

$InstrumentOutput = & $AdbExe @InstrumentArgs 2>&1
$InstrumentExit = $LASTEXITCODE

# Print raw output for debugging
Write-Host $InstrumentOutput

# ─────────────────────────────────────────────── step 12: parse result ──

Write-Step "12/13 — Parsing test result"

$TestPassed = $false
foreach ($line in $InstrumentOutput) {
    if ($line -match "OK \(\d+ test") {
        $TestPassed = $true
        break
    }
}

$TestFailed = $false
foreach ($line in $InstrumentOutput) {
    if ($line -match "FAILURES!!!" -or $line -match "FAILED \(") {
        $TestFailed = $true
        break
    }
}

# ─────────────────────────────────────────────── step 13: pull SRT + results ──

Write-Step "13/13 — Pulling subtitle files and results"

# Pull each SRT subtitle file to D:\Videos\
$SrtFiles = @("Vol_election_fr.srt", "Vol_election_en.srt", "Vol_election_es.srt")
$SrtPulled = @()
foreach ($srt in $SrtFiles) {
    $devicePath = "$SrtDeviceBase/$srt"
    $localPath  = "$SrtLocalBase\$srt"
    Write-Host "    $ & $AdbExe pull $devicePath $localPath"
    & $AdbExe pull $devicePath $localPath 2>&1
    if ($LASTEXITCODE -eq 0 -and (Test-Path $localPath)) {
        $size = [math]::Round((Get-Item $localPath).Length / 1KB, 1)
        Write-OK "Pulled: $localPath ($size KB)"
        $SrtPulled += $localPath
    } else {
        Write-Host "    WARNING: $srt not found on device (may not have been generated)." -ForegroundColor Yellow
    }
}

# Pull text results file
Write-Host "    $ & $AdbExe pull $ResultsDevice $ResultsLocal"
& $AdbExe pull $ResultsDevice $ResultsLocal 2>&1
if ($LASTEXITCODE -eq 0 -and (Test-Path $ResultsLocal)) {
    Write-OK "Results saved to $ResultsLocal"
}

# ─────────────────────────────────────────────── final verdict ──

Write-Host ""
Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor White

if ($TestPassed -and -not $TestFailed) {
    Write-Host "  SUCCES — Tous les tests WhisperKit sont passés." -ForegroundColor Green
    Write-Host ""
    if ($SrtPulled.Count -gt 0) {
        Write-Host "  Fichiers de sous-titres générés :" -ForegroundColor Cyan
        foreach ($f in $SrtPulled) { Write-Host "    $f" -ForegroundColor Cyan }
        Write-Host ""
        Write-Host "  Pour visionner avec VLC :" -ForegroundColor Yellow
        Write-Host "    1. Ouvrez D:\Videos\Vol_election.mp4 dans VLC" -ForegroundColor Yellow
        Write-Host "    2. Renommez Vol_election_fr.srt en Vol_election.srt" -ForegroundColor Yellow
        Write-Host "       → VLC le charge automatiquement comme piste FR" -ForegroundColor Yellow
        Write-Host "    3. Pour EN/ES : Sous-titres > Ajouter un fichier de sous-titres" -ForegroundColor Yellow
        Write-Host "       et sélectionnez Vol_election_en.srt ou Vol_election_es.srt" -ForegroundColor Yellow
    }
    Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor White
    exit 0
} elseif ($TestFailed) {
    Write-Host "  ECHEC — Un ou plusieurs tests ont échoué." -ForegroundColor Red
    Write-Host "  Consultez la sortie ci-dessus et logcat pour les détails." -ForegroundColor Red
    Write-Host "  $ adb logcat -s WhisperTest" -ForegroundColor Yellow
    Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor White
    exit 1
} else {
    Write-Host "  RESULTAT INCONNU — Impossible de parser la sortie de am instrument." -ForegroundColor Yellow
    Write-Host "  Sortie brute affichée ci-dessus. Code de sortie adb: $InstrumentExit" -ForegroundColor Yellow
    Write-Host "  $ adb logcat -s WhisperTest" -ForegroundColor Yellow
    Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor White
    exit $InstrumentExit
}
